services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: simple_bank
    networks:
      - simple-bank-networks

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_api
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - ADDRESS=0.0.0.0:8080
    depends_on:
      - postgres
    networks:
      - simple-bank-networks
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

networks:
  simple-bank-networks:
    driver: bridge
